/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.CreateAnimalController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Taxonomy;
import views.resources.classes.TextPrompt;

/**
 *
 * @author david
 */
public class CreateAnimal extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private CreateAnimalController controller;
    
    /**
     * Creates new form CreateProduct
     */
    public CreateAnimal() {
        initComponents();
        controller = new CreateAnimalController();
        TextPrompt pH1 = new TextPrompt("Nombre del animal", animal);
        TextPrompt pH2 = new TextPrompt("Dominio", domain);
        TextPrompt pH3 = new TextPrompt("Reino", kingdom);
        TextPrompt pH4 = new TextPrompt("Filo", phylum);
        TextPrompt pH5 = new TextPrompt("Clase", classA);
        TextPrompt pH6 = new TextPrompt("Orden", orderA);
        TextPrompt pH7 = new TextPrompt("Familia", familiy);
        TextPrompt pH8 = new TextPrompt("Género", genus);
        TextPrompt pH9 = new TextPrompt("Especie", species);
        TextPrompt pH10 = new TextPrompt("SubEspecie", subspecies);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        windowBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        closeBtn = new javax.swing.JPanel();
        iconoCerrar = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JPanel();
        iconoMinimizar = new javax.swing.JLabel();
        animal = new javax.swing.JTextField();
        subspecies = new javax.swing.JTextField();
        domain = new javax.swing.JTextField();
        kingdom = new javax.swing.JTextField();
        phylum = new javax.swing.JTextField();
        classA = new javax.swing.JTextField();
        orderA = new javax.swing.JTextField();
        familiy = new javax.swing.JTextField();
        genus = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        species = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(142, 202, 230));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowBar.setBackground(new java.awt.Color(2, 48, 71));
        windowBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowBarMouseDragged(evt);
            }
        });
        windowBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowBarMousePressed(evt);
            }
        });
        windowBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear taxonomia");
        windowBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 30));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        windowBar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        mainPanel.add(windowBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 30));

        closeBtn.setBackground(new java.awt.Color(2, 48, 71));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });

        iconoCerrar.setBackground(new java.awt.Color(37, 36, 34));
        iconoCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/cerrar15px.png"))); // NOI18N
        iconoCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout closeBtnLayout = new javax.swing.GroupLayout(closeBtn);
        closeBtn.setLayout(closeBtnLayout);
        closeBtnLayout.setHorizontalGroup(
            closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        closeBtnLayout.setVerticalGroup(
            closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, -1));

        minimizeBtn.setBackground(new java.awt.Color(2, 48, 71));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });

        iconoMinimizar.setBackground(new java.awt.Color(37, 36, 34));
        iconoMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/resources/imgs/minimizar15px.png"))); // NOI18N
        iconoMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout minimizeBtnLayout = new javax.swing.GroupLayout(minimizeBtn);
        minimizeBtn.setLayout(minimizeBtnLayout);
        minimizeBtnLayout.setHorizontalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        minimizeBtnLayout.setVerticalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconoMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 30));
        mainPanel.add(animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 270, 40));
        mainPanel.add(subspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 270, 40));
        mainPanel.add(domain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 270, 40));
        mainPanel.add(kingdom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 270, 40));
        mainPanel.add(phylum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 270, 40));
        mainPanel.add(classA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 270, 40));
        mainPanel.add(orderA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 270, 40));
        mainPanel.add(familiy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 270, 40));
        mainPanel.add(genus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 270, 40));

        addBtn.setText("Añadir");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        mainPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));
        mainPanel.add(species, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_windowBarMouseDragged

    private void windowBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_windowBarMousePressed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        closeBtn.setBackground(Color.red);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBackground(new Color(37,36,34));
    }//GEN-LAST:event_closeBtnMouseExited

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        minimizeBtn.setBackground(new Color(64, 61, 57));
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        minimizeBtn.setBackground(new Color(37,36,34));
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String animal = this.animal.getText();
        String domain = this.domain.getText();
        String kingdom = this.kingdom.getText();
        String phylum = this.phylum.getText();
        String classA = this.classA.getText();
        String orderA = this.orderA.getText();
        String family = this.familiy.getText();
        String genus = this.genus.getText();
        String species = this.species.getText();
        String subspecies = this.subspecies.getText();
        Taxonomy taxonomy = new Taxonomy(0, animal, domain, kingdom, phylum, classA, orderA, family, genus, species, subspecies);
        try {
            controller.createAnimal(taxonomy);
            volver();
        } catch (SQLException ex) {
            Logger.getLogger(CreateAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volver(){
        try {
            Main main = new Main();
            main.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ManageAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField animal;
    private javax.swing.JTextField classA;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JTextField domain;
    private javax.swing.JTextField familiy;
    private javax.swing.JTextField genus;
    private javax.swing.JLabel iconoCerrar;
    private javax.swing.JLabel iconoMinimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField kingdom;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel minimizeBtn;
    private javax.swing.JTextField orderA;
    private javax.swing.JTextField phylum;
    private javax.swing.JTextField species;
    private javax.swing.JTextField subspecies;
    private javax.swing.JPanel windowBar;
    // End of variables declaration//GEN-END:variables
}
